### ISSUE TITLE
Lag When Scrolling Some Pages

### ISSUE THREAD

**Issue by RickyM7** [Quickdesh/Animiru#24] opened 2022-12-07 18:07 UTC
### Steps to reproduce

An example, but it's occours in other pages too, like the extensions page:
1. Click on an anime with many episodes
2. Try to fast scrolling

### Expected behavior

Should be a smooth scrolling

### Actual behavior

Scrolling is hard at the moment, unlike what you see in Tachiyomi, for example

### Animiru version

0.13.4.4

### Android version

Android 11 (ArrowOs)

### Device

Xiaomi Redmi Note 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4.4](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment] 2023-01-10 16:24
will be fixed in next release

**Comment by khaled-0** [comment] 2023-01-19 12:45
Can't reproduce on One piece with 1000+ episode on my poco x4 pro

**Comment by RickyM7** [comment] 2023-01-19 15:28
> Can't reproduce on One piece with 1000+ episode on my poco x4 pro

Here you can see the Animiru behavior, it's a little sticky.

https://user-images.githubusercontent.com/24703825/213480817-f616bdfd-99ab-44a2-b02a-0d9108dee2d4.mp4

And here the Tachiyomi behavior, where scrolling is much smoother.

https://user-images.githubusercontent.com/24703825/213481014-39a0ef31-6fd8-4955-8f56-3b560ceb6739.mp4

**Comment by Quickdesh** [comment] 2023-01-19 15:33
The more you use the app, the better and faster it gets.

Plus like I said before, Animiru is way behind in commits rn. I am currently working on merging them, thus in the next release it will improve from that angle as well

**Comment by quickdesh** [comment] 2023-04-04 01:51
May feel laggy for a while more but it will get faster over time as you use it

**Closed by quickdesh** 2023-04-04 01:51 UTC
Labels: will be closed next release
